// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLrTzPdCEEwltsuEp_qtF3E3SzJrYZ1U',
    appId: '1:177664591914:web:48947e3d0d95de57331b53',
    messagingSenderId: '177664591914',
    projectId: 'newapp-c4334',
    authDomain: 'newapp-c4334.firebaseapp.com',
    databaseURL: 'https://newapp-c4334.firebaseio.com',
    storageBucket: 'newapp-c4334.appspot.com',
    measurementId: 'G-D17ZWEM8N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPSP_w5ej2TIPThT87tdvTUrVqf96Og-g',
    appId: '1:177664591914:android:85e2c28276cd0989331b53',
    messagingSenderId: '177664591914',
    projectId: 'newapp-c4334',
    databaseURL: 'https://newapp-c4334.firebaseio.com',
    storageBucket: 'newapp-c4334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDswiuJlGEb-9NIvZ7yZATvyLxS_N56VFE',
    appId: '1:177664591914:ios:9ba66883f68cc74b331b53',
    messagingSenderId: '177664591914',
    projectId: 'newapp-c4334',
    databaseURL: 'https://newapp-c4334.firebaseio.com',
    storageBucket: 'newapp-c4334.appspot.com',
    androidClientId: '177664591914-bd4c9umauu1o4vcujham8n2mdtikqsfd.apps.googleusercontent.com',
    iosClientId: '177664591914-ao62cst8ass9adjiqs2t8pfhucpel9gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectinit',
  );
}
